#!/usr/bin/perl

use strict;
use warnings;

use File::Basename 'basename';
use Cwd 'cwd';

my @machines = @ARGV;

push @machines, basename cwd unless @machines;

for my $name (@machines) {
    die "$name.machine doesn't exist\n" unless -e "$name.machine";
    die "$name.inputs doesn't exist\n" unless -e "$name.inputs";

    system "../machine2dot.pl --html < $name.machine | dot -Tpng -o $name.png";
    system "xargs ../assemble.pl $name.machine $@ < $name.inputs";
}
